spring:
  application:
    name: meal-service
  config:
    import: optional:file:/home/alamgir/Alamgir/workingProject/MBSTU_DiningPass/services/meal-service/.env[.properties]
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver


  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  web:
    error:
      include-stacktrace: never
      include-message: always
      include-binding-errors: never
      include-exception: false


services:
  auth-service:
    url: ${AUTH_SERVICE_URL}

app:
  frontend-url: ${FRONTEND_URL}

server:
  port: ${MEAL_SERVICE_SERVER_PORT}

jwt:
  secret: ${JWT_SECRET}


#  bKash Configuration
bkash:
  username: ${BKASH_USERNAME}
  password: ${BKASH_PASSWORD}
  apiKey: ${BKASH_API_KEY}
  secretKey: ${BKASH_SECRET_KEY}

  grantTokenUrl: ${BKASH_GRANT_TOKEN_URL}
  refreshTokenUrl: ${BKASH_REFRESH_TOKEN_URL}
  createPaymentUrl: ${BKASH_CREATE_PAYMENT_URL}
  executePaymentUrl: ${BKASH_EXECUTE_PAYMENT_URL}
  refundUrl: ${BKASH_REFUND_URL}
  callbackUrl: ${BKASH_CALLBACK_URL}



